// Skill content loader for the install-time file drop.
//   - Source mode: reads `<repo>/skills/<name>/SKILL.md` directly.
//   - Compiled binary: lazy-imports `./skills.compiled` (generated by
//     scripts/embed-skills.ts pre-build). The dynamic import is what keeps
//     source-mode tests resilient when the generated file is absent.
import fs from "fs";
import path from "path";

const SKILL_NAMES = [
  "instrument-agent",
  "setup-agent-replay",
] as const;
export type SkillName = (typeof SKILL_NAMES)[number];

export const SKILLS: readonly SkillName[] = SKILL_NAMES;

function isCompiledBinary(): boolean {
  return path.basename(process.execPath).toLowerCase().startsWith("raindrop");
}

let cachedSource: Record<string, string> | null = null;

async function loadAll(): Promise<Record<string, string>> {
  if (cachedSource) return cachedSource;

  if (isCompiledBinary()) {
    // Lazy dynamic import keeps source mode resilient when the generated
    // file is missing (tests, fresh clones before build).
    const mod = (await import("./skills.compiled")) as {
      EMBEDDED_SKILLS: Record<string, string>;
    };
    cachedSource = mod.EMBEDDED_SKILLS;
    return cachedSource;
  }

  const repoRoot = path.join(__dirname, "..");
  const skillsDir = path.join(repoRoot, "skills");
  const out: Record<string, string> = {};
  for (const name of SKILL_NAMES) {
    const file = path.join(skillsDir, name, "SKILL.md");
    out[name] = fs.readFileSync(file, "utf8");
  }
  cachedSource = out;
  return out;
}

export interface SkillFile {
  installName: string;
  sourceName: SkillName;
  content: string;
}

export async function getSkillFiles(): Promise<SkillFile[]> {
  const all = await loadAll();
  const out: SkillFile[] = [];
  for (const name of SKILL_NAMES) {
    const raw = all[name];
    if (raw === undefined) {
      throw new Error(
        `[init] skill "${name}" missing from embed/source. ` +
          `(Compiled binary: rebuild with \`bun run build\`. Source: ensure skills/${name}/SKILL.md exists.)`,
      );
    }
    out.push({
      installName: name,
      sourceName: name,
      content: raw,
    });
  }
  return out;
}
