#!/usr/bin/env bun
/**
 * Embed skill content into the compiled binary.
 *
 * Reads every `skills/<name>/SKILL.md` and emits `src/skills.compiled.ts`
 * with their content as string literals. The file is gitignored — it's a
 * generated build artifact, regenerated on every `bun run build`.
 *
 * `src/init-skills.ts` reads SKILL.md off disk in source mode (so iterative
 * edits to skills/ are picked up without a rebuild) and dynamically imports
 * `./skills.compiled` in compiled-binary mode. Mirrors the same pattern
 * `src/ui-assets.ts` uses for the UI tarball.
 *
 * Usage (implicit; called from build:bun script):
 *   bun scripts/embed-skills.ts
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_DIR = path.join(REPO_ROOT, "skills");
const OUT_PATH = path.join(REPO_ROOT, "src", "skills.compiled.ts");

function listSkills(): { name: string; content: string }[] {
  const entries = readdirSync(SKILLS_DIR, { withFileTypes: true });
  const out: { name: string; content: string }[] = [];
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const skillFile = path.join(SKILLS_DIR, entry.name, "SKILL.md");
    try {
      statSync(skillFile);
    } catch {
      continue;
    }
    out.push({
      name: entry.name,
      content: readFileSync(skillFile, "utf8"),
    });
  }
  return out;
}

function escapeForBacktickString(s: string): string {
  // Backtick-string literals only need to escape: backslash, backtick,
  // and ${. Newlines are preserved verbatim.
  return s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function main(): void {
  const skills = listSkills();
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/embed-skills.ts. Do not edit by hand.",
    "// Regenerated on every build from the contents of skills/<name>/SKILL.md.",
    "",
    "export const EMBEDDED_SKILLS: Record<string, string> = {",
  ];
  for (const { name, content } of skills) {
    lines.push(`  ${JSON.stringify(name)}: \`${escapeForBacktickString(content)}\`,`);
  }
  lines.push("};");
  lines.push("");
  writeFileSync(OUT_PATH, lines.join("\n"));
  console.log(
    `[embed-skills] wrote ${path.relative(REPO_ROOT, OUT_PATH)} (${skills.length} skills: ${skills
      .map((s) => s.name)
      .join(", ")})`,
  );
}

main();
