#!/usr/bin/env bun
/**
 * Generate the static migration asset manifest used by compiled Bun binaries.
 *
 * Drizzle's SQLite migrator wants a real migrations folder on disk. Source mode
 * can use ./drizzle directly, but the installed single-file binary cannot rely
 * on loose repository files. This script emits static `with { type: "file" }`
 * imports for every journaled SQL migration so Bun embeds them at compile time.
 *
 * Usage:
 *   bun scripts/embed-migrations.ts
 *   bun scripts/embed-migrations.ts --check
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

type MigrationJournal = {
  version: string;
  dialect: string;
  entries: Array<{
    idx: number;
    tag: string;
    [key: string]: unknown;
  }>;
};

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const DRIZZLE_DIR = path.join(REPO_ROOT, "drizzle");
const JOURNAL_PATH = path.join(DRIZZLE_DIR, "meta", "_journal.json");
const OUT_PATH = path.join(REPO_ROOT, "src", "db", "migration-assets.ts");

function parseArgs(): { check: boolean } {
  let check = false;
  for (const arg of process.argv.slice(2)) {
    if (arg === "--check") check = true;
    else if (arg === "--help" || arg === "-h") {
      console.log("Usage: bun scripts/embed-migrations.ts [--check]");
      process.exit(0);
    } else {
      console.error(`Unknown arg: ${arg}`);
      process.exit(2);
    }
  }
  return { check };
}

function readJournal(): MigrationJournal {
  if (!existsSync(JOURNAL_PATH)) {
    throw new Error(`Missing Drizzle journal: ${path.relative(REPO_ROOT, JOURNAL_PATH)}`);
  }
  const journal = JSON.parse(readFileSync(JOURNAL_PATH, "utf8")) as MigrationJournal;
  if (!Array.isArray(journal.entries)) {
    throw new Error(`Invalid Drizzle journal: entries must be an array`);
  }
  return journal;
}

function buildSource(): string {
  const journal = readJournal();
  const entries = [...journal.entries].sort((a, b) => a.idx - b.idx);
  const sqlFiles = readdirSync(DRIZZLE_DIR)
    .filter((name) => name.endsWith(".sql"))
    .sort();

  const migrationFiles = entries.map((entry) => {
    if (!Number.isInteger(entry.idx) || entry.idx < 0) {
      throw new Error(`Invalid migration idx for tag ${JSON.stringify(entry.tag)}`);
    }
    if (!entry.tag || typeof entry.tag !== "string") {
      throw new Error(`Invalid migration tag at idx ${entry.idx}`);
    }
    const fileName = `${entry.tag}.sql`;
    const fullPath = path.join(DRIZZLE_DIR, fileName);
    if (!existsSync(fullPath)) {
      throw new Error(`Journal references missing migration: ${path.relative(REPO_ROOT, fullPath)}`);
    }
    return {
      fileName,
      varName: `migration${String(entry.idx).padStart(4, "0")}Path`,
    };
  });

  const journalFileSet = new Set(migrationFiles.map((file) => file.fileName));
  const extraSqlFiles = sqlFiles.filter((file) => !journalFileSet.has(file));
  if (extraSqlFiles.length > 0) {
    throw new Error(
      `Found migration SQL files missing from drizzle/meta/_journal.json: ${extraSqlFiles.join(", ")}`,
    );
  }

  const lines: string[] = [
    "// AUTO-GENERATED by scripts/embed-migrations.ts. Do not edit by hand.",
    "// Source of truth: drizzle/meta/_journal.json and drizzle/*.sql.",
    "// Run `bun run db:generate` after changing src/db/schema.ts.",
    "",
  ];

  for (const file of migrationFiles) {
    lines.push(
      `import ${file.varName} from ${JSON.stringify(`../../drizzle/${file.fileName}`)} with { type: "file" };`,
    );
  }

  lines.push("");
  lines.push(`export const embeddedMigrationJournal = ${JSON.stringify(journal, null, 2)} as const;`);
  lines.push("");
  lines.push("export const embeddedMigrationFiles = [");
  for (const file of migrationFiles) {
    lines.push("  {");
    lines.push(`    relativePath: ${JSON.stringify(file.fileName)},`);
    lines.push(`    sourcePath: ${file.varName},`);
    lines.push("  },");
  }
  lines.push("] as const;");
  lines.push("");
  return lines.join("\n");
}

function main(): void {
  const { check } = parseArgs();
  const next = buildSource();
  if (check) {
    const current = existsSync(OUT_PATH) ? readFileSync(OUT_PATH, "utf8") : "";
    if (current !== next) {
      console.error(
        `[embed-migrations] ${path.relative(REPO_ROOT, OUT_PATH)} is stale. ` +
          `Run \`bun scripts/embed-migrations.ts\` or \`bun run db:generate\`.`,
      );
      process.exit(1);
    }
    console.log(`[embed-migrations] ${path.relative(REPO_ROOT, OUT_PATH)} is up to date`);
    return;
  }

  writeFileSync(OUT_PATH, next);
  const journal = readJournal();
  console.log(
    `[embed-migrations] wrote ${path.relative(REPO_ROOT, OUT_PATH)} ` +
      `(${journal.entries.length} migrations)`,
  );
}

main();
