// AUTO-GENERATED by scripts/embed-migrations.ts. Do not edit by hand.
// Source of truth: drizzle/meta/_journal.json and drizzle/*.sql.
// Run `bun run db:generate` after changing src/db/schema.ts.

import migration0000Path from "../../drizzle/0000_massive_winter_soldier.sql" with { type: "file" };
import migration0001Path from "../../drizzle/0001_cynical_betty_brant.sql" with { type: "file" };
import migration0002Path from "../../drizzle/0002_observer_steering_events.sql" with { type: "file" };

export const embeddedMigrationJournal = {
  "version": "7",
  "dialect": "sqlite",
  "entries": [
    {
      "idx": 0,
      "version": "6",
      "when": 1778475472563,
      "tag": "0000_massive_winter_soldier",
      "breakpoints": true
    },
    {
      "idx": 1,
      "version": "6",
      "when": 1778475541625,
      "tag": "0001_cynical_betty_brant",
      "breakpoints": true
    },
    {
      "idx": 2,
      "version": "6",
      "when": 1780166400000,
      "tag": "0002_observer_steering_events",
      "breakpoints": true
    }
  ]
} as const;

export const embeddedMigrationFiles = [
  {
    relativePath: "0000_massive_winter_soldier.sql",
    sourcePath: migration0000Path,
  },
  {
    relativePath: "0001_cynical_betty_brant.sql",
    sourcePath: migration0001Path,
  },
  {
    relativePath: "0002_observer_steering_events.sql",
    sourcePath: migration0002Path,
  },
] as const;
